---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - dp.wso2.com
  resources:
  - apis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dp.wso2.com
  resources:
  - apis/finalizers
  verbs:
  - update
- apiGroups:
  - dp.wso2.com
  resources:
  - apis/status
  verbs:
  - get
  - patch
  - update
